--Journey Through the Dream World
local s, id = GetID()
function s.initial_effect(c)
	local e1 = Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET+EFFECT_FLAG_DAMAGE_STEP)
	e1:SetCategory(CATEGORY_ATKCHANGE+CATEGORY_DEFCHANGE)
	e1:SetHintTiming(TIMING_DAMAGE_STEP)
	e1:SetTarget(s.target)
	e1:SetOperation(s.activate)
	c:RegisterEffect(e1)
end
function s.target(e, tp, eg, ep, ev, re, r, rp, chk, chkc)
	if chkc then return false end
	if chk == 0 then return Duel.IsExistingTarget(aux.FilterFaceupFunction(Card.IsAttribute, ATTRIBUTE_DREAM), tp, LOCATION_MZONE, 0, 1, nil)
		and Duel.IsExistingTarget(Card.IsFaceup, tp, 0, LOCATION_MZONE, 1, nil) end
	Duel.Hint(HINT_SELECTMSG, tp, HINTMSG_FACEUP)
	Duel.SelectTarget(tp, aux.FilterFaceupFunction(Card.IsAttribute, ATTRIBUTE_DREAM), tp, LOCATION_MZONE, 0, 1, 1, nil)
	Duel.Hint(HINT_SELECTMSG, tp, HINTMSG_FACEUP)
	Duel.SelectTarget(tp, Card.IsFaceup, tp, 0, LOCATION_MZONE, 1, 1, nil)
end
function s.activate(e, tp, eg, ep, ev, re, r, rp)
	local c = e:GetHandler()
	local g = Duel.GetChainInfo(0, CHAININFO_TARGET_CARDS)
	local tc1 = g:GetFirst()
	local tc2 = g:GetNext()
	if tc1:IsFaceup() and tc2:IsFaceup() and tc1:IsRelateToEffect(e) and tc2:IsRelateToEffect(e) then
		local atk1, def1 = tc1:GetAttack(), tc1:GetDefense()
		local atk2, def2 = tc2:GetAttack(), tc2:GetDefense()
		local e1 = Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_SET_ATTACK)
		e1:SetValue(atk2)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
		tc1:RegisterEffect(e1)
		local e2 = e1:Clone()
		e2:SetValue(atk1)
		tc2:RegisterEffect(e2)
		local e3 = e1:Clone()
		e3:SetCode(EFFECT_SET_DEFENSE)
		e3:SetValue(def2)
		tc1:RegisterEffect(e3)
		local e4 = e3:Clone()
		e4:SetValue(def1)
		tc2:RegisterEffect(e4)
	end
end
